language: python

before_install:
  - sudo cp -R server/bulk_extractor/ /usr/share/bulk_extractor/

install:
  - pip install tox 
  - pip install psycopg2

script:
  - tox

matrix:
  include:

    - python: "3.6"
      env: TOXENV=py36

    - python: "3.6"
      env: TOXENV=py36-flake8